blank_issues_enabled: false
contact_links:
  - name: ConoHaサポート窓口
    url: https://support.conoha.jp/inquiry/
    about: ConoHaのサポート窓口です。なお、本ConoHa VPS MCPに関しては、ConoHaのサポート窓口では対応できませんので、GitHubのIssueを利用してください。
