name: Publish to GitHub Packages

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      packages: write

    steps:
      # 1) ソース取得
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # 2) ブランチ名からバージョン抽出
      - name: Extract version from branch name
        id: extract
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          if [[ "$BRANCH_NAME" =~ ^release\/(v[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Not a release branch. Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      # 3) タグ付け
      - name: Tag and push
        if: success() && steps.extract.outputs.skip != 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch --tags
          git tag ${{ steps.extract.outputs.VERSION }}
          git push origin ${{ steps.extract.outputs.VERSION }}

      # 4) Node セットアップ
      - name: Setup Node.js
        if: success() && steps.extract.outputs.skip != 'true'
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22.17.0"
          registry-url: "https://npm.pkg.github.com"
          scope: "@gmo-internet"

      # 5) 依存インストール
      - name: Install dependencies
        if: success() && steps.extract.outputs.skip != 'true'
        run: npm ci

      # 6) ビルド
      - name: Build project
        if: success() && steps.extract.outputs.skip != 'true'
        run: npm run build

      # 7) RC 用のパッケージ名調整
      - name: Set package name for RC versions
        if: success() && steps.extract.outputs.skip != 'true'
        run: |
          VERSION='${{ steps.extract.outputs.VERSION }}'
          if [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ ]]; then
            npm pkg set name="@gmo-internet/priv-conoha-vps-mcp"
          fi

      # 8) 公開
      - name: Publish to GitHub Packages
        if: success() && steps.extract.outputs.skip != 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
