name: Publish to GitHub Packages

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
          scope: "@gmo-internet"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Set package name for RC versions
        run: |
          if [[ "${{ github.ref_name }}" =~ v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+ ]]; then
            npm pkg set name="@gmo-internet/priv-conoha-vps-mcp"
          fi

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
