name: Push to Public Repository
on:
  push:
    branches:
      - staging # FIXME: change to main

permissions:
  contents: write

jobs:
  push-to-public:
    uses: gmo-internet/priv_share/.github/workflows/publish.yml@main
    secrets: inherit
