name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Extract repository name
        run: |
          priv_repo=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)
          public_repo=${priv_repo#priv_}
          echo "priv_repo=${priv_repo}" >> "$GITHUB_ENV"
          echo "public_repo=${public_repo}" >> "$GITHUB_ENV"

      - name: Generate GitHub Apps token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_PUSH_TO_PUBLIC_ID }}
          private-key: ${{ secrets.APP_PUSH_TO_PUBLIC_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ env.priv_repo }}
            ${{ env.public_repo }}

      - name: Release Please action
        uses: googleapis/release-please-action@1155c2c8dcbd6b15e85bae6bc6d1fed9552663cb
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: node
