name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Extract repository name
        run: |
          repository_name=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)
          echo "repository_name=${repository_name}" >> "$GITHUB_ENV"

      - name: Generate GitHub Apps token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ secrets.APP_PUSH_TO_PUBLIC_ID }}
          private-key: ${{ secrets.APP_PUSH_TO_PUBLIC_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ env.repository_name }}

      - name: Release Please action
        uses: googleapis/release-please-action@1155c2c8dcbd6b15e85bae6bc6d1fed9552663cb
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
