name: Tag on PR Merge (from release branch)

on:
  pull_request:
    types: [closed]

jobs:
  tag_on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from branch name
        id: extract
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          if [[ "$BRANCH_NAME" =~ ^release\/([0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?)$ ]]; then
            VERSION="v${BASH_REMATCH[1]}"
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Not a release branch. Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Tag and push
        if: steps.extract.outputs.skip != 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch --tags
          git tag ${{ steps.extract.outputs.VERSION }}
          git push origin ${{ steps.extract.outputs.VERSION }}
